ideal_price: 550
key_mode: false
max_price: 748
rolling_loop_interval: 50
hoarding_loop_interval: 150
item_type: 0
use_balance_calculation: true
trading_mode: 0
rolling_option: 2
rolling_options:
  - buy_price: 518
    min_buy_price: 300
    buy_count: 4980
    fast_sell_threshold: 200000
  - buy_price: 3000
    min_buy_price: 1000
    buy_count: 4980
    fast_sell_threshold: 5000
  - buy_price: 3900
    min_buy_price: 1500
    buy_count: 4980
    fast_sell_threshold: 15000
  - buy_price: 1600
    min_buy_price: 600
    buy_count: 4980
    fast_sell_threshold: 20000
screen_width: 2560
screen_height: 1440
auto_sell: true
fast_sell: true
log_level: INFO
second_detect: true
switch_to_battlefield: true
switch_to_battlefield_count: 400
