ideal_price: 568
key_mode: false
max_price: 628
rolling_loop_interval: 50
hoarding_loop_interval: 500
item_type: 0
use_balance_calculation: true
trading_mode: 1
rolling_option: 0
rolling_options:
- buy_price: 578
  min_buy_price: 300
  buy_count: 4980
- buy_price: 450
  min_buy_price: 300
  buy_count: 4980
- buy_price: 450
  min_buy_price: 270
  buy_count: 4980
- buy_price: 1700
  min_buy_price: 700
  buy_count: 1740
screen_width: 2560
screen_height: 1440
auto_sell: true
fast_sell: true
fast_sell_threshold: 200000
log_level: INFO
